In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/final_dataset.csv")

In [3]:
df.head()

                                                text     emotion
0  i feel rather funny ending with so many dupes ...         fun
1                     i feel surprised by the result    surprise
2                    i am officially feeling festive     neutral
3  i suddenly found myself standing before this w...    surprise
4  i look at the meager pile of food i purchased ...  enthusiasm

In [4]:
df['text']=df['text'].str.lower()

In [5]:
df['text'].head()

0    i feel rather funny ending with so many dupes ...
1                       i feel surprised by the result
2                      i am officially feeling festive
3    i suddenly found myself standing before this w...
4    i look at the meager pile of food i purchased ...
Name: text, dtype: object

In [6]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk

In [7]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [8]:
stop_words=set(stopwords.words('english'))

lematiser=WordNetLemmatizer()

In [9]:
def process_text(text):
  word_tokens=word_tokenize(text)
  filter_tokens=[word for word in word_tokens if word.lower() not in stop_words]
  lematized_tokens=[lematiser.lemmatize(word.lower()) for word in filter_tokens]

  return {
      'orginal_text':text,
      'word_tokens':word_tokens,
      'filter_tokens':filter_tokens,
      'lematized_tokens':lematized_tokens

  }

In [10]:
result=df['text'].apply(process_text)
processed_df=pd.DataFrame(result.tolist())
print(processed_df.head())

                                        orginal_text  \
0  i feel rather funny ending with so many dupes ...
1                     i feel surprised by the result
2                    i am officially feeling festive
3  i suddenly found myself standing before this w...
4  i look at the meager pile of food i purchased ...

                                         word_tokens  \
0  [i, feel, rather, funny, ending, with, so, man...
1              [i, feel, surprised, by, the, result]
2              [i, am, officially, feeling, festive]
3  [i, suddenly, found, myself, standing, before,...
4  [i, look, at, the, meager, pile, of, food, i, ...

                                       filter_tokens  \
0  [feel, rather, funny, ending, many, dupes, alw...
1                          [feel, surprised, result]
2                     [officially, feeling, festive]
3  [suddenly, found, standing, woman, dressed, li...
4  [look, meager, pile, food, purchased, week, fe...

                                    lematized_tokens
0  [feel, rather, funny, ending, many, dupe, alwa...
1                          [feel, surprised, result]
2                     [officially, feeling, festive]
3  [suddenly, found, standing, woman, dressed, li...
4  [look, meager, pile, food, purchased, week, fe...

In [11]:
print('\n before stopword removal')
df['text']

 before stopword removal

0         i feel rather funny ending with so many dupes ...
1                            i feel surprised by the result
2                           i am officially feeling festive
3         i suddenly found myself standing before this w...
4         i look at the meager pile of food i purchased ...
                                ...
106350    i used to feel strongly about how much i hated...
106351    i feel like i just got a spirit booster this r...
106352    i could come up with is that i was really feel...
106353    i find it really it helps to have an outfit of...
106354    i can t help feeling surprised by his sudden call
Name: text, Length: 106355, dtype: object

In [12]:
print('\n after stop word removal')
processed_df['filter_tokens']

 after stop word removal

0         [feel, rather, funny, ending, many, dupes, alw...
1                                 [feel, surprised, result]
2                            [officially, feeling, festive]
3         [suddenly, found, standing, woman, dressed, li...
4         [look, meager, pile, food, purchased, week, fe...
                                ...
106350    [used, feel, strongly, much, hated, curly, fee...
106351    [feel, like, got, spirit, booster, refers, ama...
106352    [could, come, really, feeling, victimized, mad...
106353    [find, really, helps, outfit, favourite, basic...
106354             [help, feeling, surprised, sudden, call]
Name: filter_tokens, Length: 106355, dtype: object

In [13]:
import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer,PorterStemmer
from nltk.tokenize import word_tokenize

In [14]:
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [15]:
lematiser=WordNetLemmatizer()

In [16]:
stemmer = PorterStemmer()

def lemmatize_text(text):
    tokens = word_tokenize(str(text))
    return ' '.join([lemmatizer.lemmatize(word) for word in tokens])

def stem_text(text):
    tokens = word_tokenize(str(text))
    return ' '.join([stemmer.stem(word) for word in tokens])

In [18]:
from nltk.stem import WordNetLemmatizer,PorterStemmer
from nltk.tokenize import word_tokenize

# Define lemmatizer and stemmer here, ensuring they are in scope for the functions
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

# Redefine the functions to use the lemmatizer and stemmer defined in this cell
def lemmatize_text(text):
    tokens = word_tokenize(str(text))
    return ' '.join([lemmatizer.lemmatize(word) for word in tokens])

def stem_text(text):
    tokens = word_tokenize(str(text))
    return ' '.join([stemmer.stem(word) for word in tokens])

df['lemmatized_text'] = df['text'].apply(lemmatize_text)
df['stemmed_text'] = df['text'].apply(stem_text)